baseurl      = ""
title        = "Matsu Dev Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[author]
  name       = "Matsu"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Abusing Javascript and The Web"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Matsu Blog - Blog about Javascript and abusing the web platform"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name    = "twitter"
    url     = "https://twitter.com/matsuuu_"

  [[params.social]]
    name    = "github"
    url     = "https://github.com/Matsuuu"

  [[params.social]]
    name    = "linkedin"
    url     = "https://www.linkedin.com/in/matias-huhta-b0b159106/"


[taxonomies]
    category = "posts"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Matsu"
    subtitle = "Abusing Javascript and The Web platform"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = ":wq"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[markup.goldmark.renderer]
    unsafe = true
